[font]
size = 13.0

[font.normal]
family = "PragmataPro Nerd Font"
style = "Regular"

[font.bold]
family = "PragmataPro Nerd Font"
style = "Bold"

[font.italic]
family = "PragmataPro Nerd Font"
style = "Italic"

[font.bold_italic]
family = "PragmataPro Nerd Font"
style = "Bold Italic"
