[general]
import = [
    "~/.config/alacritty/themes/cyberdream_custom.toml"
    # "~/.config/alacritty/themes/tangere.toml"
]

[font]
size = 13.0

[window]
opacity = 0.85  # 1.0 = opaque, 0.0 = fully transparent

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"
